const VIDEOS = {
  "Tiger King": "https://youtu.be/acTdxsoa428",
  "Amanda Knox": "https://youtu.be/mRLt2xBpQbQ",
  "Citizenfour": "https://youtu.be/XiGwAvd5mvM",
  "Super Size Me": "https://youtu.be/GRPSeVyrd68",
  "Man on Wire": "https://youtu.be/Cz6oddi0mts",
  "The Office": "https://youtu.be/LHOtME2DL4g",
  "Arrested Development": "https://youtu.be/TntmMY7N8ag",
  "Curb Your Enthusiasm": "https://youtu.be/u7bnE6XiOEQ",
  "Family Guy": "https://youtu.be/Le1x2To-e6g",
  "South Park": "https://youtu.be/8F16zdxynlg",
  "Peppa Pig": "https://youtu.be/F5MGoX1Atnc",
  "Dora The Explorer": "https://youtu.be/F5MGoX1Atnc",
  "PAW Patrol": "https://youtu.be/eOYL8qQxxPw",
  "Arthur": "https://youtu.be/j40YC5d6RzA",
  "SpongeBob": "https://youtu.be/a2cowVH03Xo",
  "Making a Murderer": "https://youtu.be/qxgbdYaR_KQ",
  "Long Shot": "https://youtu.be/S5jiaHvx-kY",
  "The Confession Killer": "https://youtu.be/mWPbC9Fp-yk",
  "The Innocent Man": "https://youtu.be/4LYiAEV_XnA",
  "The Staircase": "https://youtu.be/Bvv97sCcruY",
  "Good Will Hunting": "https://youtu.be/PaZVjZEFkRs",
  "Forrest Gump": "https://youtu.be/bLvqoHBptjg",
  "Juno": "https://youtu.be/K0SKf0K3bxg",
  "Midnight In Paris": "https://youtu.be/FAfR8omt-CY",
  "School of Rock": "https://youtu.be/TExoc0MG4I4",
  "The Prestige": "https://youtu.be/RLtaA9fFNXU",
  "Fight Club": "https://youtu.be/qtRKdVHc-cE",
  "Kings Speech": "https://youtu.be/EcxBrTvLbBM",
  "The Revenant": "https://youtu.be/LoebZZ8K5N0",
  "The Social Network": "https://youtu.be/lB95KLmpLR4",
  "Shutter Island": "https://youtu.be/5iaYLCiq5RM",
  "Gone Girl": "https://youtu.be/2-_-1nJf8Vg",
  "Prisoners": "https://youtu.be/bpXfcTF6iVk",
  "Seven": "https://youtu.be/znmZoVkCjpI",
  "Zodiac": "https://youtu.be/yNncHPl1UXg",
  "Hotel Transylvania": "https://youtu.be/q4RK3jY7AVk",
  "Despicable Me": "https://youtu.be/zzCZ1W_CUoI",
  "Frozen": "https://youtu.be/TbQm5doF_Uc",
  "Spirited Away": "https://youtu.be/ByXuk9QqQkk",
  "Up": "https://youtu.be/ORFWdXl_zJ4",
  "Joker": "https://youtu.be/zAGVQLHvwOY",
  "A Quiet Place": "https://youtu.be/WR7cc5t7tv8",
  "Black Swan": "https://youtu.be/5jaI1XOB-bs",
  "Nightcrawler": "https://youtu.be/u1uP_8VJkDQ",
  "The Silence of The Lambs": "https://youtu.be/W6Mm8Sbe__o",
  "A Star Is Born": "https://youtu.be/nSbzyEJ8X9E",
  "Blue Valentine": "https://youtu.be/aILx69WrRhQ",
  "La La Land": "https://youtu.be/0pdqf4P9MB8",
  "The Notebook": "https://youtu.be/yDJIcYE32NU?t=1",
  "Titanic": "https://youtu.be/kVrqfYjkTdQ",
};

export default VIDEOS;